version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /conf/sampleapp.json
    destination: /etc/consul.d/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/reload_consul
      timeout: 300
  ValidateService:
    - location: scripts/validate
      timeout: 60
